#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$ROOT_DIR/delivery-date-estimator"
SCHEMA_PATH="$APP_DIR/prisma/schema.prisma"
MIGRATIONS_DIR="$APP_DIR/prisma/migrations"
STAMP="$(date +%Y%m%d%H%M%S)"

if [[ -z "${DATABASE_URL:-}" ]]; then
  echo "DATABASE_URL is required."
  exit 1
fi

if [[ ! "${DATABASE_URL}" =~ ^postgres(ql)?:// ]]; then
  echo "DATABASE_URL must be a postgres connection string."
  exit 1
fi

echo "Starting Prisma Postgres cutover at ${STAMP}"

cp "${SCHEMA_PATH}" "${SCHEMA_PATH}.bak.${STAMP}"
if [[ -d "${MIGRATIONS_DIR}" ]]; then
  cp -R "${MIGRATIONS_DIR}" "${MIGRATIONS_DIR}.bak.${STAMP}"
fi

perl -0pi -e 's/provider = "sqlite"/provider = "postgresql"/g' "${SCHEMA_PATH}"
perl -0pi -e 's/url\s*=\s*"file:dev\.sqlite"/url      = env("DATABASE_URL")/g' "${SCHEMA_PATH}"

rm -rf "${MIGRATIONS_DIR}"
mkdir -p "${MIGRATIONS_DIR}/${STAMP}_init_postgres"

cat > "${MIGRATIONS_DIR}/migration_lock.toml" <<'EOF'
# Please do not edit this file manually
# It should be added in your version-control system (e.g., Git)
provider = "postgresql"
EOF

(
  cd "${APP_DIR}"
  npx prisma migrate diff \
    --from-empty \
    --to-schema-datamodel prisma/schema.prisma \
    --script \
    > "prisma/migrations/${STAMP}_init_postgres/migration.sql"

  npx prisma generate --schema prisma/schema.prisma
  npx prisma migrate deploy --schema prisma/schema.prisma
)

echo "Postgres cutover complete."
echo "Review changes and commit:"
echo "  git status"
echo "  git add ${APP_DIR}/prisma"
echo "  git commit -m 'Migrate Prisma datasource to PostgreSQL'"
